### ISSUE TITLE
Make TLS certificate validation configurable

### ISSUE THREAD

**Issue by ckunki** [exasol/exasol-python-test-framework#66] opened 2024-07-04 15:21 UTC
EPTF generates file `odbc.ini` containing the configuration options for the ODBC driver. 

Newer versions of Exasol database validate the TLS certificates and may cause an error when using a self-signed certificate. 

Such error messages can be suppressed by adding option `;FINGERPRINT=NoCertCheck` to the DSN in file `odbc.ini`.
This option cannot be appended to CLI option `--server`.

### Acceptance Criteria 

The current ticket requests to add a new CLI option to EPTF controlling whether this option should be added.

Additionally, in [client_setup.py#L61](https://github.com/exasol/exasol-python-test-framework/blob/master/exasol_python_test_framework/exatest/clients/client_setup.py#L61) the suffix `.logdir` should be removed.

**Comment by redcatbear** [comment] 2024-07-05 09:21
Duplicate of #63.

**Closed** 2024-07-08 07:56 UTC
Labels: feature
